language: node_js
node_js:
 - "8"

branches:
 only:
  - master

install:
- npm install

script:
- npm run-script build
- npm test

before_deploy:
- ./scripts/prepare-deployment.sh

deploy:
- skip_cleanup: true
  provider: firebase
  on:
    branch: master
  token:
    secure: "$FIREBASE_SECRET"
  project: "achievements-prod"

