language: node_js
node_js:
 - "8"

branches:
 only:
  - develop

install:
- npm install

script:
- npm run-script build

before_deploy:
- cp src/achievementsApp/altConfig.js src/achievementsApp/config.js
- ./scripts/travis-install-functions.sh

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "$FIREBASE_SECRET"
  project: "fir-project-3d2a4"
