language: node_js
node_js:
 - "8"

branches:
 only:
  - master

before_install:
- npm config set //registry.npmjs.org/:_authToken $NPM_API_KEY

install:
- npm install -g firebase-tools
- npm install

script:
- npm run-script build
- npm run-script coverage

before_deploy:
- ./scripts/prepare-deployment.sh

after_success:
- ./scripts/prepare-deployment.sh
- firebase deploy --project "achievements-dev" --token $FIREBASE_SECRET --only hosting

# deploy:
# - skip_cleanup: true
  # provider: firebase
  # on:
    # branch: master
  # token:
    # secure: "$FIREBASE_SECRET"
  # project: "achievements-dev"
