language: node_js
node_js:
  - "8"

branches:
  only:
    - master

before_install:
  - npm config set //registry.npmjs.org/:_authToken $NPM_API_KEY

install:
  - npm install

script:
  - npm run-script test
  # - npm run-script build

after_success:
  - echo "TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST TRAVIS_BRANCH=$TRAVIS_BRANCH"
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      echo "test if exit works";
      exit
    else
      npm install -g firebase-tools;
      echo "only deploy for merge to master, not PR";
    fi
  - firebase deploy --token $FIREBASE_SECRET --project achievements-dev --only hosting,database

# deploy:
# # use bash script to customize firebase deploy
# # we skip functions in firebase
  # - skip_cleanup: true
    # provider: script
    # script: bash scripts/deployment.sh
    # on:
      # branch: master
    # message: "deployment done"
